swagger: '2.0'
info:
  title: 'Storehouse API definition'
  description: 'TODO description'
  version: '1'
  contact: 'syuilinnikita@gmail.com'
basePath: '/api/v1'

securityDefinitions:
  Bearer:
    type: 'apiKey'
    name: 'Authorization'
    in: 'header'
    description: 'JWT Authorization header using the Bearer scheme'

definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
  Video:
    type: object
    properties:
      id:
        type: integer
      owner_id:
        type: integer
      title:
        type: string
      episodes:
        type: integer
      is_series:
        type: boolean
      upload_date:
        type: date
      score:
        type: float
      duration:
        type: float

  Watchlist:
    type: object
    properties:
      id:
        type: integer
      user_id:
        type: integer
      target_id:
        type: integer
      target_type:
        type: string
      score:
        type: float
      episodes:
        type: integer
      rewatches:
        type: integer
